// Code generated by MockGen. DO NOT EDIT.
// Source: nfqueue/interfaces.go

// Package mock_nfqueue is a generated GoMock package.
package mock_nfqueue

import (
	context "context"
	reflect "reflect"
	syscall "syscall"

	gomock "github.com/golang/mock/gomock"
	common "go.aporeto.io/netlink-go/common"
	nfqueue "go.aporeto.io/netlink-go/nfqueue"
)

// MockVerdict is a mock of Verdict interface
type MockVerdict struct {
	ctrl     *gomock.Controller
	recorder *MockVerdictMockRecorder
}

// MockVerdictMockRecorder is the mock recorder for MockVerdict
type MockVerdictMockRecorder struct {
	mock *MockVerdict
}

// NewMockVerdict creates a new mock instance
func NewMockVerdict(ctrl *gomock.Controller) *MockVerdict {
	mock := &MockVerdict{ctrl: ctrl}
	mock.recorder = &MockVerdictMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockVerdict) EXPECT() *MockVerdictMockRecorder {
	return m.recorder
}

// SetVerdict2 mocks base method
func (m *MockVerdict) SetVerdict2(queueNum, verdict, mark, packetLen, packetID uint32, packet []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetVerdict2", queueNum, verdict, mark, packetLen, packetID, packet)
}

// SetVerdict2 indicates an expected call of SetVerdict2
func (mr *MockVerdictMockRecorder) SetVerdict2(queueNum, verdict, mark, packetLen, packetID, packet interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVerdict2", reflect.TypeOf((*MockVerdict)(nil).SetVerdict2), queueNum, verdict, mark, packetLen, packetID, packet)
}

// SetVerdict mocks base method
func (m *MockVerdict) SetVerdict(queueNum, verdict, packetLen, packetID uint32, packet []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetVerdict", queueNum, verdict, packetLen, packetID, packet)
}

// SetVerdict indicates an expected call of SetVerdict
func (mr *MockVerdictMockRecorder) SetVerdict(queueNum, verdict, packetLen, packetID, packet interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVerdict", reflect.TypeOf((*MockVerdict)(nil).SetVerdict), queueNum, verdict, packetLen, packetID, packet)
}

// GetNotificationChannel mocks base method
func (m *MockVerdict) GetNotificationChannel() chan *nfqueue.NFPacket {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationChannel")
	ret0, _ := ret[0].(chan *nfqueue.NFPacket)
	return ret0
}

// GetNotificationChannel indicates an expected call of GetNotificationChannel
func (mr *MockVerdictMockRecorder) GetNotificationChannel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationChannel", reflect.TypeOf((*MockVerdict)(nil).GetNotificationChannel))
}

// StopQueue mocks base method
func (m *MockVerdict) StopQueue() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopQueue")
	ret0, _ := ret[0].(error)
	return ret0
}

// StopQueue indicates an expected call of StopQueue
func (mr *MockVerdictMockRecorder) StopQueue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopQueue", reflect.TypeOf((*MockVerdict)(nil).StopQueue))
}

// MockNFQueue is a mock of NFQueue interface
type MockNFQueue struct {
	ctrl     *gomock.Controller
	recorder *MockNFQueueMockRecorder
}

// MockNFQueueMockRecorder is the mock recorder for MockNFQueue
type MockNFQueueMockRecorder struct {
	mock *MockNFQueue
}

// NewMockNFQueue creates a new mock instance
func NewMockNFQueue(ctrl *gomock.Controller) *MockNFQueue {
	mock := &MockNFQueue{ctrl: ctrl}
	mock.recorder = &MockNFQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNFQueue) EXPECT() *MockNFQueueMockRecorder {
	return m.recorder
}

// SetVerdict2 mocks base method
func (m *MockNFQueue) SetVerdict2(queueNum, verdict, mark, packetLen, packetID uint32, packet []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetVerdict2", queueNum, verdict, mark, packetLen, packetID, packet)
}

// SetVerdict2 indicates an expected call of SetVerdict2
func (mr *MockNFQueueMockRecorder) SetVerdict2(queueNum, verdict, mark, packetLen, packetID, packet interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVerdict2", reflect.TypeOf((*MockNFQueue)(nil).SetVerdict2), queueNum, verdict, mark, packetLen, packetID, packet)
}

// SetVerdict mocks base method
func (m *MockNFQueue) SetVerdict(queueNum, verdict, packetLen, packetID uint32, packet []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetVerdict", queueNum, verdict, packetLen, packetID, packet)
}

// SetVerdict indicates an expected call of SetVerdict
func (mr *MockNFQueueMockRecorder) SetVerdict(queueNum, verdict, packetLen, packetID, packet interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVerdict", reflect.TypeOf((*MockNFQueue)(nil).SetVerdict), queueNum, verdict, packetLen, packetID, packet)
}

// GetNotificationChannel mocks base method
func (m *MockNFQueue) GetNotificationChannel() chan *nfqueue.NFPacket {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationChannel")
	ret0, _ := ret[0].(chan *nfqueue.NFPacket)
	return ret0
}

// GetNotificationChannel indicates an expected call of GetNotificationChannel
func (mr *MockNFQueueMockRecorder) GetNotificationChannel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationChannel", reflect.TypeOf((*MockNFQueue)(nil).GetNotificationChannel))
}

// StopQueue mocks base method
func (m *MockNFQueue) StopQueue() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopQueue")
	ret0, _ := ret[0].(error)
	return ret0
}

// StopQueue indicates an expected call of StopQueue
func (mr *MockNFQueueMockRecorder) StopQueue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopQueue", reflect.TypeOf((*MockNFQueue)(nil).StopQueue))
}

// NfqOpen mocks base method
func (m *MockNFQueue) NfqOpen() (nfqueue.SockHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NfqOpen")
	ret0, _ := ret[0].(nfqueue.SockHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NfqOpen indicates an expected call of NfqOpen
func (mr *MockNFQueueMockRecorder) NfqOpen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NfqOpen", reflect.TypeOf((*MockNFQueue)(nil).NfqOpen))
}

// UnbindPf mocks base method
func (m *MockNFQueue) UnbindPf() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnbindPf")
	ret0, _ := ret[0].(error)
	return ret0
}

// UnbindPf indicates an expected call of UnbindPf
func (mr *MockNFQueueMockRecorder) UnbindPf() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnbindPf", reflect.TypeOf((*MockNFQueue)(nil).UnbindPf))
}

// CreateQueue mocks base method
func (m *MockNFQueue) CreateQueue(num uint16, data func(*nfqueue.NFPacket, interface{}), errorCallback func(error, interface{}), privateData interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQueue", num, data, errorCallback, privateData)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateQueue indicates an expected call of CreateQueue
func (mr *MockNFQueueMockRecorder) CreateQueue(num, data, errorCallback, privateData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQueue", reflect.TypeOf((*MockNFQueue)(nil).CreateQueue), num, data, errorCallback, privateData)
}

// NfqSetMode indicates an expected call of NfqSetMode
func (mr *MockNFQueueMockRecorder) NfqSetMode(mode, packetSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NfqSetMode", reflect.TypeOf((*MockNFQueue)(nil).NfqSetMode), mode, packetSize)
}

// NfqSetQueueMaxLen mocks base method
func (m *MockNFQueue) NfqSetQueueMaxLen(queuelen uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NfqSetQueueMaxLen", queuelen)
	ret0, _ := ret[0].(error)
	return ret0
}

// NfqSetQueueMaxLen indicates an expected call of NfqSetQueueMaxLen
func (mr *MockNFQueueMockRecorder) NfqSetQueueMaxLen(queuelen interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NfqSetQueueMaxLen", reflect.TypeOf((*MockNFQueue)(nil).NfqSetQueueMaxLen), queuelen)
}

// NfqClose mocks base method
func (m *MockNFQueue) NfqClose() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NfqClose")
}

// NfqClose indicates an expected call of NfqClose
func (mr *MockNFQueueMockRecorder) NfqClose() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NfqClose", reflect.TypeOf((*MockNFQueue)(nil).NfqClose))
}

// NfqDestroyQueue mocks base method
func (m *MockNFQueue) NfqDestroyQueue() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NfqDestroyQueue")
	ret0, _ := ret[0].(error)
	return ret0
}

// NfqDestroyQueue indicates an expected call of NfqDestroyQueue
func (mr *MockNFQueueMockRecorder) NfqDestroyQueue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NfqDestroyQueue", reflect.TypeOf((*MockNFQueue)(nil).NfqDestroyQueue))
}

// Recv mocks base method
func (m *MockNFQueue) Recv() (*common.NfqGenMsg, map[int]*common.NfAttrResponsePayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*common.NfqGenMsg)
	ret1, _ := ret[1].(map[int]*common.NfAttrResponsePayload)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Recv indicates an expected call of Recv
func (mr *MockNFQueueMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockNFQueue)(nil).Recv))
}

// ProcessPackets mocks base method
func (m *MockNFQueue) ProcessPackets(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessPackets", ctx)
}

// ProcessPackets indicates an expected call of ProcessPackets
func (mr *MockNFQueueMockRecorder) ProcessPackets(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPackets", reflect.TypeOf((*MockNFQueue)(nil).ProcessPackets), ctx)
}

// BindPf mocks base method
func (m *MockNFQueue) BindPf() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindPf")
	ret0, _ := ret[0].(error)
	return ret0
}

// BindPf indicates an expected call of BindPf
func (mr *MockNFQueueMockRecorder) BindPf() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindPf", reflect.TypeOf((*MockNFQueue)(nil).BindPf))
}

// setSockHandle mocks base method
func (m *MockNFQueue) setSockHandle(handle nfqueue.SockHandle) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "setSockHandle", handle)
}

// setSockHandle indicates an expected call of setSockHandle
func (mr *MockNFQueueMockRecorder) setSockHandle(handle interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "setSockHandle", reflect.TypeOf((*MockNFQueue)(nil).setSockHandle), handle)
}

// MockSockHandle is a mock of SockHandle interface
type MockSockHandle struct {
	ctrl     *gomock.Controller
	recorder *MockSockHandleMockRecorder
}

// MockSockHandleMockRecorder is the mock recorder for MockSockHandle
type MockSockHandleMockRecorder struct {
	mock *MockSockHandle
}

// NewMockSockHandle creates a new mock instance
func NewMockSockHandle(ctrl *gomock.Controller) *MockSockHandle {
	mock := &MockSockHandle{ctrl: ctrl}
	mock.recorder = &MockSockHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSockHandle) EXPECT() *MockSockHandleMockRecorder {
	return m.recorder
}

// query mocks base method
func (m *MockSockHandle) query(msg *syscall.NetlinkMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "query", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// query indicates an expected call of query
func (mr *MockSockHandleMockRecorder) query(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "query", reflect.TypeOf((*MockSockHandle)(nil).query), msg)
}

// recv mocks base method
func (m *MockSockHandle) recv() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "recv")
	ret0, _ := ret[0].(error)
	return ret0
}

// recv indicates an expected call of recv
func (mr *MockSockHandleMockRecorder) recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "recv", reflect.TypeOf((*MockSockHandle)(nil).recv))
}

// send mocks base method
func (m *MockSockHandle) send(msg *syscall.NetlinkMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "send", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// send indicates an expected call of send
func (mr *MockSockHandleMockRecorder) send(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "send", reflect.TypeOf((*MockSockHandle)(nil).send), msg)
}

// getFd mocks base method
func (m *MockSockHandle) getFd() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getFd")
	ret0, _ := ret[0].(int)
	return ret0
}

// getFd indicates an expected call of getFd
func (mr *MockSockHandleMockRecorder) getFd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getFd", reflect.TypeOf((*MockSockHandle)(nil).getFd))
}

// getRcvBufSize mocks base method
func (m *MockSockHandle) getRcvBufSize() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getRcvBufSize")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// getRcvBufSize indicates an expected call of getRcvBufSize
func (mr *MockSockHandleMockRecorder) getRcvBufSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getRcvBufSize", reflect.TypeOf((*MockSockHandle)(nil).getRcvBufSize))
}

// getLocalAddress mocks base method
func (m *MockSockHandle) getLocalAddress() syscall.SockaddrNetlink {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getLocalAddress")
	ret0, _ := ret[0].(syscall.SockaddrNetlink)
	return ret0
}

// getLocalAddress indicates an expected call of getLocalAddress
func (mr *MockSockHandleMockRecorder) getLocalAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getLocalAddress", reflect.TypeOf((*MockSockHandle)(nil).getLocalAddress))
}

// close mocks base method
func (m *MockSockHandle) close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "close")
}

// close indicates an expected call of close
func (mr *MockSockHandleMockRecorder) close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "close", reflect.TypeOf((*MockSockHandle)(nil).close))
}
